import type { Cooperative, Producer, Parcel, Agent } from '../types'

export const MOCK_COOPERATIVES: Cooperative[] = [
  {
    id: 'coop-001',
    name: 'COOPACI BEOUMI',
    rccm: 'CI-ABJ-2018-B-12345',
    agrement: 'MINADER/2018/001',
    pca: 'KOUAME Thierry',
    adg: 'YAO Jean-Baptiste',
    director: 'KONAN Marcellin',
    sigManager: 'BAMBA Issouf',
    phone: '+225 27 31 63 00 00',
    email: 'coopaci@beoumi.ci',
    address: 'Beoumi, Centre, Côte d\'Ivoire',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    isActive: true,
    createdAt: '2024-01-10',
    producerCount: 245,
    parcelCount: 312,
    totalHectares: 875.4,
    agentCount: 8,
  },
  {
    id: 'coop-002',
    name: 'COOP CAFÉ DALOA',
    rccm: 'CI-ABJ-2019-B-67890',
    agrement: 'MINADER/2019/002',
    pca: 'OUATTARA Seydou',
    adg: 'COULIBALY Abdoulaye',
    director: 'BERTE Mamadou',
    sigManager: 'KONE Aminata',
    phone: '+225 27 32 00 00 00',
    email: 'coopcafe@daloa.ci',
    address: 'Daloa, Haut-Sassandra, Côte d\'Ivoire',
    region: 'Haut-Sassandra',
    country: 'Côte d\'Ivoire',
    isActive: true,
    createdAt: '2024-02-15',
    producerCount: 189,
    parcelCount: 234,
    totalHectares: 612.8,
    agentCount: 6,
  },
  {
    id: 'coop-003',
    name: 'ANACACI SAN PEDRO',
    rccm: 'CI-ABJ-2020-B-11223',
    agrement: 'MINADER/2020/003',
    pca: 'DIALLO Ibrahima',
    adg: 'TRAORE Fatoumata',
    director: 'CAMARA Lansana',
    sigManager: 'FOFANA Salimata',
    phone: '+225 27 34 00 00 00',
    email: 'anacaci@sanpedro.ci',
    address: 'San Pédro, San Pédro, Côte d\'Ivoire',
    region: 'San Pédro',
    country: 'Côte d\'Ivoire',
    isActive: true,
    createdAt: '2024-03-01',
    producerCount: 310,
    parcelCount: 428,
    totalHectares: 1245.6,
    agentCount: 12,
  },
]

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent-001',
    userId: '3',
    cooperativeId: 'coop-001',
    code: 'AG-BEOU-001',
    fullName: 'Kouassi Bernard',
    phone: '+225 07 00 00 01',
    email: 'k.bernard@geocollect.ci',
    zone: 'Zone Nord-Beoumi',
    isActive: true,
    createdAt: '2024-02-01',
    parcelCount: 87,
    hectares: 243.2,
    lastActivity: '2024-12-18',
  },
  {
    id: 'agent-002',
    userId: '4',
    cooperativeId: 'coop-001',
    code: 'AG-BEOU-002',
    fullName: 'Traoré Aminata',
    phone: '+225 07 00 00 02',
    email: 'a.traore@geocollect.ci',
    zone: 'Zone Sud-Beoumi',
    isActive: true,
    createdAt: '2024-02-01',
    parcelCount: 72,
    hectares: 198.6,
    lastActivity: '2024-12-17',
  },
  {
    id: 'agent-003',
    userId: '5',
    cooperativeId: 'coop-001',
    code: 'AG-BEOU-003',
    fullName: 'Diallo Mamadou',
    phone: '+225 07 00 00 03',
    email: 'm.diallo@geocollect.ci',
    zone: 'Zone Est-Beoumi',
    isActive: true,
    createdAt: '2024-02-15',
    parcelCount: 65,
    hectares: 178.4,
    lastActivity: '2024-12-16',
  },
]

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: 'prod-001',
    cooperativeId: 'coop-001',
    fieldIdBase: 'BEOUMI000001',
    firstName: 'Jean',
    lastName: 'KONAN',
    fullName: 'KONAN Jean',
    phone: '+225 07 11 22 33',
    village: 'Akakro',
    section: 'BEOUMI',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    gender: 'M',
    birthYear: 1975,
    isActive: true,
    createdAt: '2024-03-01',
    assignedAgentId: 'agent-001',
    parcelCount: 3,
    totalHectares: 8.4,
  },
  {
    id: 'prod-002',
    cooperativeId: 'coop-001',
    fieldIdBase: 'BEOUMI000002',
    firstName: 'Marie',
    lastName: 'KOUASSI',
    fullName: 'KOUASSI Marie',
    phone: '+225 07 22 33 44',
    village: 'Kpouebo',
    section: 'BEOUMI',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    gender: 'F',
    birthYear: 1982,
    isActive: true,
    createdAt: '2024-03-05',
    assignedAgentId: 'agent-001',
    parcelCount: 2,
    totalHectares: 5.6,
  },
  {
    id: 'prod-003',
    cooperativeId: 'coop-001',
    fieldIdBase: 'BEOUMI000003',
    firstName: 'Yao',
    lastName: 'ATTA',
    fullName: 'ATTA Yao',
    phone: '+225 07 33 44 55',
    village: 'Broukro',
    section: 'BODOKRO',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    gender: 'M',
    birthYear: 1968,
    isActive: true,
    createdAt: '2024-03-10',
    assignedAgentId: 'agent-002',
    parcelCount: 4,
    totalHectares: 12.1,
  },
  {
    id: 'prod-004',
    cooperativeId: 'coop-001',
    fieldIdBase: 'BEOUMI000004',
    firstName: 'Fatou',
    lastName: 'COULIBALY',
    fullName: 'COULIBALY Fatou',
    phone: '+225 07 44 55 66',
    village: 'Diabo',
    section: 'BODOKRO',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    gender: 'F',
    birthYear: 1979,
    isActive: true,
    createdAt: '2024-03-12',
    assignedAgentId: 'agent-002',
    parcelCount: 1,
    totalHectares: 3.2,
  },
  {
    id: 'prod-005',
    cooperativeId: 'coop-001',
    fieldIdBase: 'BEOUMI000005',
    firstName: 'Kofi',
    lastName: 'ASSI',
    fullName: 'ASSI Kofi',
    phone: '+225 07 55 66 77',
    village: 'Niamoue',
    section: 'SAKASSOU',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    gender: 'M',
    birthYear: 1971,
    isActive: true,
    createdAt: '2024-03-15',
    assignedAgentId: 'agent-003',
    parcelCount: 2,
    totalHectares: 6.8,
  },
]

// Polygons in Côte d'Ivoire (Beoumi region approx)
const makePolygon = (lat: number, lng: number, size = 0.003) => ({
  type: 'Polygon' as const,
  coordinates: [[
    [lng, lat],
    [lng + size, lat],
    [lng + size, lat + size],
    [lng, lat + size * 0.8],
    [lng - size * 0.1, lat + size * 0.4],
    [lng, lat],
  ]],
})

export const MOCK_PARCELS: Parcel[] = [
  {
    id: 'parc-001',
    fieldId: 'BEOUMI000001-M001',
    producerId: 'prod-001',
    cooperativeId: 'coop-001',
    agentId: 'agent-001',
    name: 'Parcelle Nord',
    geometry: makePolygon(7.672, -5.681),
    areaHectares: 2.8,
    perimeterMeters: 712,
    vertexCount: 6,
    culture: 'Cacao',
    village: 'Akakro',
    section: 'BEOUMI',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    status: 'validated',
    eudrScore: 94,
    eudrStatus: 'compliant',
    isSynced: true,
    createdAt: '2024-06-15',
    updatedAt: '2024-06-15',
  },
  {
    id: 'parc-002',
    fieldId: 'BEOUMI000001-M002',
    producerId: 'prod-001',
    cooperativeId: 'coop-001',
    agentId: 'agent-001',
    name: 'Parcelle Sud',
    geometry: makePolygon(7.668, -5.678),
    areaHectares: 3.1,
    perimeterMeters: 798,
    vertexCount: 5,
    culture: 'Cacao',
    village: 'Akakro',
    section: 'BEOUMI',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    status: 'validated',
    eudrScore: 88,
    eudrStatus: 'compliant',
    isSynced: true,
    createdAt: '2024-06-16',
    updatedAt: '2024-06-16',
  },
  {
    id: 'parc-003',
    fieldId: 'BEOUMI000002-M001',
    producerId: 'prod-002',
    cooperativeId: 'coop-001',
    agentId: 'agent-001',
    name: 'Parcelle Principale',
    geometry: makePolygon(7.662, -5.690, 0.004),
    areaHectares: 4.2,
    perimeterMeters: 920,
    vertexCount: 7,
    culture: 'Cacao',
    village: 'Kpouebo',
    section: 'BEOUMI',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    status: 'rejected',
    eudrScore: 45,
    eudrStatus: 'non_compliant',
    isSynced: true,
    createdAt: '2024-07-02',
    updatedAt: '2024-07-02',
  },
  {
    id: 'parc-004',
    fieldId: 'BEOUMI000003-M001',
    producerId: 'prod-003',
    cooperativeId: 'coop-001',
    agentId: 'agent-002',
    name: 'Grande Parcelle',
    geometry: makePolygon(7.680, -5.665, 0.005),
    areaHectares: 5.6,
    perimeterMeters: 1100,
    vertexCount: 8,
    culture: 'Café',
    village: 'Broukro',
    section: 'BODOKRO',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    status: 'pending',
    eudrScore: 72,
    eudrStatus: 'pending',
    isSynced: true,
    createdAt: '2024-08-10',
    updatedAt: '2024-08-10',
  },
  {
    id: 'parc-005',
    fieldId: 'BEOUMI000005-M001',
    producerId: 'prod-005',
    cooperativeId: 'coop-001',
    agentId: 'agent-003',
    name: 'Parcelle Familiale',
    geometry: makePolygon(7.658, -5.695, 0.0025),
    areaHectares: 1.9,
    perimeterMeters: 560,
    vertexCount: 5,
    culture: 'Cacao',
    village: 'Niamoue',
    section: 'SAKASSOU',
    region: 'Bélier',
    country: 'Côte d\'Ivoire',
    status: 'validated',
    eudrScore: 97,
    eudrStatus: 'compliant',
    isSynced: false,
    createdAt: '2024-09-05',
    updatedAt: '2024-09-05',
  },
]
